/**
 * GET /api/games/trivia/daily
 *
 * Returns 10 trivia questions about African and diaspora culture,
 * generated by Gemini and cached in-process for the calendar day.
 *
 * Cache key: YYYY-MM-DD in UTC. On cold starts the batch is regenerated —
 * acceptable for a hobby-plan Vercel deployment.
 *
 * Response:
 *   { date, questions: Array<{ question, options, correct, explanation }> }
 *
 * correct is 0-based index into options[].
 */

import { NextResponse } from "next/server";
import { GoogleGenAI, HarmCategory, HarmBlockThreshold } from "@google/genai";

export const runtime = "nodejs";

interface TriviaQuestion {
  question:    string;
  options:     [string, string, string, string];
  correct:     number;
  explanation: string;
  category:    string;
}

// ── In-process day cache ──────────────────────────────────────────────────────
let cachedDate      = "";
let cachedQuestions: TriviaQuestion[] = [];

// ── Gemini setup ──────────────────────────────────────────────────────────────
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY ?? "" });

const SAFETY = [
  { category: HarmCategory.HARM_CATEGORY_HARASSMENT,        threshold: HarmBlockThreshold.BLOCK_NONE },
  { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,       threshold: HarmBlockThreshold.BLOCK_NONE },
  { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE },
];

const TEXT_MODELS = ["gemini-2.5-flash", "gemini-2.5-flash-lite"];

const PROMPT = `You are the question writer for Culture Games — a trivia game on The Moveee, a platform celebrating African and diaspora culture globally.

Generate exactly 10 trivia questions. Cover a diverse mix of categories:
- Afrobeats, Afropop, Highlife, Amapiano, Afro-soul, African jazz (2 questions)
- Nollywood, African cinema, Black British/American film and TV (2 questions)
- African literature, Caribbean literature, Harlem Renaissance, diaspora fiction (2 questions)
- African history, politics, independence movements, civil rights (2 questions)
- African visual art, fashion, food, and traditions (2 questions)

Rules:
- All questions must be factual and verifiable — no invented trivia
- Difficulty: 4 easy, 4 medium, 2 hard
- Each question has exactly 4 options (A–D), only one correct
- The correct option should appear in all positions (A, B, C, D) across different questions, distributed somewhat evenly
- Write a brief 1–2 sentence explanation for each answer that adds cultural context

Return ONLY a valid JSON array — no markdown, no code fences:
[
  {
    "question": "...",
    "options": ["option A", "option B", "option C", "option D"],
    "correct": 0,
    "explanation": "...",
    "category": "music | film | literature | history | culture"
  }
]`;

function extractJson(raw: string): string {
  const s = raw.indexOf("[");
  const e = raw.lastIndexOf("]");
  if (s === -1 || e === -1) throw new Error("No JSON array in response");
  return raw.slice(s, e + 1);
}

async function generateQuestions(): Promise<TriviaQuestion[]> {
  let lastErr: any;

  for (const model of TEXT_MODELS) {
    try {
      const res = await ai.models.generateContent({
        model,
        contents: PROMPT,
        config: {
          responseMimeType: "application/json",
          safetySettings: SAFETY,
        },
      });

      const raw = (res.text ?? "").trim();
      if (!raw) continue;

      const parsed = JSON.parse(extractJson(raw));
      if (!Array.isArray(parsed) || parsed.length === 0) continue;

      const questions: TriviaQuestion[] = parsed
        .filter(
          (q: any) =>
            q.question &&
            Array.isArray(q.options) &&
            q.options.length === 4 &&
            typeof q.correct === "number" &&
            q.correct >= 0 &&
            q.correct <= 3
        )
        .slice(0, 10)
        .map((q: any) => ({
          question:    String(q.question),
          options:     q.options.map(String) as [string, string, string, string],
          correct:     Number(q.correct),
          explanation: String(q.explanation ?? ""),
          category:    String(q.category ?? "culture"),
        }));

      if (questions.length >= 5) return questions;
    } catch (err) {
      lastErr = err;
    }
  }

  throw new Error(`Trivia generation failed: ${lastErr?.message}`);
}

export async function GET() {
  const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD UTC

  if (cachedDate === today && cachedQuestions.length > 0) {
    return NextResponse.json({ date: today, questions: cachedQuestions });
  }

  try {
    const questions = await generateQuestions();
    cachedDate      = today;
    cachedQuestions = questions;
    return NextResponse.json({ date: today, questions });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
