const raw = `"All that you touch you change. All that you change changes you. The only lasting truth is change.","Octavia E. Butler","Parable of the Sower"
"Do not be afraid to disappear. From it, from us, for a while, and see what comes to you in the silence.","Michaela Coel","2018 MacTaggart Lecture"
"Art is man's constant effort to create for himself a different order of reality from that which is given to him.","Chinua Achebe","Hopes and Impediments"
"Know from whence you came. If you know whence you came, there are absolutely no limitations to where you can go.","James Baldwin","The Fire Next Time"
"I'm rooting for everybody Black.","Issa Rae","70th Primetime Emmy Awards Red Carpet"
"The past is always tense, the future perfect.","Zadie Smith","White Teeth"
"Everything I do is for the 17-year-old version of myself.","Virgil Abloh","2017 Columbia GSAPP Lecture"
"How do we make black cinema with the power, beauty, and alienation of black music?","Arthur Jafa","Filmmaker Magazine Interview"
"If I didn't define myself for myself, I would be crunched into other people's fantasies for me and eaten alive.","Audre Lorde","Learning from the 60s"
"Cinema is an evening school. People don’t go to the cinema to learn, but they learn anyway.","Ousmane Sembène","Various Interviews"
"I don't think about art when I'm working. I try to think about life.","Jean-Michel Basquiat","1985 Interview with Tamra Davis"
"Culture does not make people. People make culture. If it is true that the full humanity of women is not our culture, then we can and must make it our culture.","Chimamanda Ngozi Adichie","We Should All Be Feminists"
"You can't go on all the time being whatever's necessary. You've got to have some conviction, and I'm convinced I don't want to be anyone's underdog.","Tsitsi Dangarembga","Nervous Conditions"
"In the world through which I travel, I am endlessly creating myself.","Frantz Fanon","Black Skin, White Masks"
"I think for a long time I was looking to the world to give me permission to be who I was. And at a certain point I just stopped.","Barry Jenkins","2016 Moonlight Press Tour"
"No one leaves home unless home is the mouth of a shark.","Warsan Shire","Teaching My Mother Have to Give Birth"
"I didn’t want to make a film about the dead, but about the ghosts left behind.","Mati Diop","2019 Interview on 'Atlantics'"
"My mouth shall be the mouth of those calamities that have no mouth.","Aimé Césaire","Notebook of a Return to the Native Land"
"I am interested in the future, because that is where I am going to spend the rest of my life.","Djibril Diop Mambéty","Various Interviews"
"If there's a book that you want to read, but it hasn't been written yet, then you must write it.","Toni Morrison","1981 Speech at the Ohio Arts Council"
"Music is the weapon of the future.","Fela Kuti","Various Interviews"
"The greatest threat to freedom is the absence of criticism.","Wole Soyinka","The Man Died: Prison Notes"
"A people without the knowledge of their past history, origin and culture is like a tree without roots.","Marcus Garvey","Garvey and Garveyism"
"I am not African because I was born in Africa but because Africa was born in me.","Kwame Nkrumah","Africa Must Unite"
"To be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.","Nelson Mandela","Long Walk to Freedom"
"Books saved you. They became your passport to the world.","Mariama Bâ","So Long a Letter"
"Humans, not places, make memories.","Ama Ata Aidoo","Changes: A Love Story"
"Language, any language, has a dual character: it is both a means of communication and a carrier of culture.","Ngũgĩ wa Thiong'o","Decolonising the Mind"
"Don't ask where I'm from, ask where I'm a local.","Taiye Selasi","TED Talk 2014"
"To be alive is to be a traveler.","Teju Cole","Open City"
"Identities are the names we give to the different ways we are positioned by, and position ourselves within, the narratives of the past.","Stuart Hall","Cultural Identity and Diaspora"
"The black Atlantic is a culture that is not specifically African, American, Caribbean, or British, but all of these at once.","Paul Gilroy","The Black Atlantic"
"We are a storytelling species.","Sylvia Wynter","On Being Human as Praxis"
"The function of art is to do more than tell it like it is—it's to imagine what is possible.","bell hooks","Outlaw Culture"
"We believe the one who has power. He is the one who gets to write the story. So when you study history, you must ask yourself, Whose story am I missing?","Yaa Gyasi","Homegoing"
"We are all children of blood and bone.","Tomi Adeyemi","Children of Blood and Bone"
"African science fiction's blood runs deep, it's old, and it's ready to come forth.","Nnedi Okorafor","TED Talk 2017"
"It has to be black folks telling our own stories. We have to document our history ourselves.","Spike Lee","Do the Right Thing Press Tour"
"If your dream only includes you, it's too small.","Ava DuVernay","2015 SXSW Keynote"
"I think when you're making a movie, you're making a movie for yourself.","Ryan Coogler","2018 Black Panther Interview"
"I try to make films that are like a song.","John Singleton","Various Interviews"
"I saw that the camera could be a weapon against poverty, against racism, against all sorts of social wrongs.","Gordon Parks","A Choice of Weapons"
"What I choose to do is to take people who happen to look like me—black and brown—people all over the world, and to elevate them on a field of power.","Kehinde Wiley","2015 Brooklyn Museum Retrospective"
"No matter where you're from, your dreams are valid.","Lupita Nyong'o","2014 Academy Awards Acceptance Speech"
"Cinema is a tool for returning to oneself.","Mati Diop","Various Interviews"
"The archive is not simply a repository of the past; it is a way of understanding the present.","John Akomfrah","The Unfinished Conversation"
"Space is the place.","Sun Ra","Space Is the Place"
"Science fiction isn't just thinking about the world out there. It's also thinking about how that world might be—a particularly important exercise for those who are marginalized in the here-and-now.","Samuel R. Delany","Racism and Science Fiction"
"Embrace what makes you unique, even if it makes others uncomfortable.","Janelle Monáe","2018 Dirty Computer Press"
"Afrofuturism bridges the gap between the past and the future, the human and the cosmic.","Ytasha L. Womack","Afrofuturism: The World of Black Sci-Fi and Fantasy Culture"
"The future belongs to those who can imagine it.","Kodwo Eshun","More Brilliant Than the Sun"
"Some worlds are built on a fault line of pain, held up by nightmares.","N.K. Jemisin","The Fifth Season"
"The story of the black experience in the Americas is a story of ghosts.","Marlon James","2019 Interview"
"The role of the artist is to make the revolution irresistible.","Toni Cade Bambara","The Black Woman: An Anthology"
"I am not tragically colored. There is no great sorrow dammed up in my soul, nor lurking behind my eyes.","Zora Neale Hurston","How It Feels to Be Colored Me"
"You may not control all the events that happen to you, but you can decide not to be reduced by them.","Maya Angelou","Letter to My Daughter"
"Nobody's free until everybody's free.","Fannie Lou Hamer","1971 National Women's Political Caucus"
"Truth is powerful and it prevails.","Sojourner Truth","1851 Women's Rights Convention"
"If there is no struggle, there is no progress.","Frederick Douglass","1857 West India Emancipation Speech"
"The most common way people give up their power is by thinking they don't have any.","Alice Walker","Various Interviews"
"An artist's duty, as far as I'm concerned, is to reflect the times.","Nina Simone","1968 Interview"
"Emancipate yourselves from mental slavery. None but ourselves can free our minds.","Bob Marley","Redemption Song"
"Knowledge is power. Information is liberating. Education is the premise of progress.","Kofi Annan","1997 Speech"
"A system cannot fail those it was never meant to protect.","W.E.B. Du Bois","Various Writings"
"The secret to my success is just believing in myself and believing in my origins.","Burna Boy","2020 Grammy Press"
"Create dangerously, for people who read dangerously.","Edwidge Danticat","Create Dangerously"
"If you want to make a human being into a monster, deny them, at the cultural level, any reflection of themselves.","Junot Díaz","2012 Interview"
"A revolution is first and foremost a movement from the old to the new.","C.L.R. James","The Black Jacobins"
"You cannot carry out fundamental change without a certain amount of madness.","Thomas Sankara","1985 Interview"
"The most potent weapon in the hands of the oppressor is the mind of the oppressed.","Steve Biko","I Write What I Like"
"To poison a nation, poison its stories. A poisoned nation has no future.","Ben Okri","A Way of Being Free"
"Every dictator is a coward.","Nuruddin Farah","Various Interviews"
"I want to be remembered as the person who helped people see Africa in a different way.","Binyavanga Wainaina","How to Write About Africa"
"If Africans do not tell their own stories, Africa will soon disappear.","Ousmane Sembène","1970s Filmmaking Lectures"
"It is not about saving the world. It is about saving ourselves.","Raoul Peck","I Am Not Your Negro Press Tour"
"Joy is an act of resistance.","Wanuri Kahiu","2018 TED Talk"
"Nature is the most advanced technology we have.","Nnedi Okorafor","Binti"
"The alien is always a reflection of ourselves.","Tade Thompson","Rosewater"
"I am a bridge between worlds.","Akwaeke Emezi","Freshwater"
"Fairy tales are not just for children. They are for the soul.","Helen Oyeyemi","Boy, Snow, Bird Interviews"
"A myth is a truth that is too big to be a fact.","Marlon James","Black Leopard, Red Wolf Press"
"A woman's place is in the world.","Buchi Emecheta","Second Class Citizen"
"The past is a foreign country, but it is also our home.","Chigozie Obioma","The Fishermen"
"War does not break women; it remakes them.","Maaza Mengiste","The Shadow King"
"There is a beautiful kind of tragedy in being an immigrant.","Dinaw Mengestu","The Beautiful Things That Heaven Bears"
"Ways of dying are also ways of living.","Zakes Mda","Ways of Dying"
"A human being is a human being through other human beings.","Pumla Gobodo-Madikizela","A Human Being Died That Night"
"My humanity is bound up in yours, for we can only be human together.","Desmond Tutu","No Future Without Forgiveness"
"History is a clock that people use to tell their political and cultural time of day.","John Henrik Clarke","African People in World History"
"It is our duty to fight for our freedom. It is our duty to win.","Assata Shakur","Assata: An Autobiography"
"I am no longer accepting the things I cannot change. I am changing the things I cannot accept.","Angela Davis","Various Speeches"
"Education is the passport to the future, for tomorrow belongs to those who prepare for it today.","Malcolm X","1964 OAAU Founding Rally"
"If they don't give you a seat at the table, bring a folding chair.","Shirley Chisholm","Unbought and Unbossed"
"The way to right wrongs is to turn the light of truth upon them.","Ida B. Wells","The Light of Truth"
"The American Negro must remake his past in order to make his future.","Arturo Schomburg","The Negro Digs Up His Past"
"Start where you are. Use what you have. Do what you can.","Arthur Ashe","Days of Grace"
"The master's tools will never dismantle the master's house.","Audre Lorde","Sister Outsider"
"I am deliberate and afraid of nothing.","Audre Lorde","New Year's Day"
"Every generation must, out of relative obscurity, discover its mission, fulfill it, or betray it.","Frantz Fanon","The Wretched of the Earth"
"The single story creates stereotypes, and the problem with stereotypes is not that they are untrue, but that they are incomplete.","Chimamanda Ngozi Adichie","The Danger of a Single Story"
"There is always light. If only we're brave enough to see it. If only we're brave enough to be it.","Amanda Gorman","The Hill We Climb"
"If you surrender to the air, you could ride it.","Toni Morrison","Song of Solomon"
"Not everything that is faced can be changed, but nothing can be changed until it is faced.","James Baldwin","As Much Truth as One Can Bear"
"Freedom is not something that anybody can be given. Freedom is something people take.","James Baldwin","Nobody Knows My Name"
"The English language is nobody's special property. It is the property of the imagination.","Derek Walcott","The Antilles: Fragments of Epic Memory"
"We demand the right to opacity.","Édouard Glissant","Poetics of Relation"
"Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.","Langston Hughes","Dreams"
"We are each other's harvest; we are each other's business; we are each other's magnitude and bond.","Gwendolyn Brooks","Paul Robeson"
"Won't you celebrate with me what i have shaped into a kind of life? i had no model.","Lucille Clifton","won't you celebrate with me"
"Where there is a woman there is magic.","Ntozake Shange","For Colored Girls Who Have Considered Suicide / When the Rainbow Is Enuf"
"If we don’t write ourselves into history, we will be written out of it.","Bernardine Evaristo","Various Interviews"
"When I discover who I am, I’ll be free.","Ralph Ellison","Invisible Man"
"Men can starve from a lack of self-realization as much as they can from a lack of bread.","Richard Wright","Native Son"
"If we must die, let it not be like hogs.","Claude McKay","If We Must Die"
"The past is a heavy burden, but it is also the foundation upon which we build the future.","Maryse Condé","I, Tituba, Black Witch of Salem"
"The word becomes the poem, the poem becomes the drum, the drum becomes the heartbeat.","Kamau Brathwaite","Roots"
"A country without literature is a country without a soul.","Alain Mabanckou","Various Interviews"
"To write is to constantly face the terror of your own limitations.","Chris Abani","The Face: Cartography of the Void"
"There is no African identity that is not at the same time a global identity.","Achille Mbembe","Out of the Dark Night"
"A culture is a total way of life.","Walter Rodney","How Europe Underdeveloped Africa"
"Always bear in mind that the people are not fighting for ideas, for the things in anyone’s head.","Amílcar Cabral","Tell No Lies, Claim No Easy Victories"
"Dead, living, free, or in prison on the orders of the colonialists, it is not I who counts.","Patrice Lumumba","Letter to his wife, Pauline"
"It’s the little things citizens do. That’s what will make the difference.","Wangari Maathai","Various Interviews"
"I do not sing politics, I merely sing the truth.","Miriam Makeba","Makeba: My Story"
"A riot is the language of the unheard.","Martin Luther King Jr.","The Other America"
"You can jail a Revolutionary, but you can't jail the Revolution.","Huey P. Newton","Revolutionary Suicide"
"Black power is giving power to people who have not had power to determine their destiny.","Kwame Ture","1966 Speech at UC Berkeley"
"Justice is what love looks like in public.","Cornel West","Various Interviews"
"My music is the spiritual expression of what I am — my faith, my knowledge, my being.","John Coltrane","A Love Supreme Liner Notes"
"Sometimes you have to play a long time to be able to play like yourself.","Miles Davis","Various Interviews"
"I got loyalty, got royalty inside my DNA.","Kendrick Lamar","DNA."
"Do nothing without intention.","Solange Knowles","A Seat at the Table Press"
"I broke the curse with my own two hands.","Beyoncé","Lemonade"
"I am trying to establish a presence of blackness that is absolutely incontrovertible.","Kerry James Marshall","Various Interviews"
"I want to challenge the viewer to see beyond the surface.","Lorna Simpson","Museum Retrospective"
"I am a woman, I am an artist, I am a black woman. I am all of those things at once.","Carrie Mae Weems","Various Interviews"
"I wanted to see a Black woman on the screen who was not a victim.","Julie Dash","Daughters of the Dust Press Tour"
"Film is a way to give people their dignity.","Charles Burnett","Killer of Sheep Commentary"
"I want to be a mirror. I want to reflect what's going on.","Steve McQueen","12 Years a Slave Press Tour"
"We are the aliens we've been waiting for.","Nalo Hopkinson","Midnight Robber"
"Cinema is a way to capture the soul of a people.","Souleymane Cissé","Cannes Film Festival Interview"
"My films are my weapons. My camera is my gun.","Haile Gerima","Sankofa Press"
"The beautiful ones are not yet born.","Ayi Kwei Armah","The Beautyful Ones Are Not Yet Born"
"I am the history of my own body.","Kei Miller","The Cartographer Tries to Map a Way to Zion"
"To be an island woman is to be the sea.","Safiya Sinclair","Cannibal"
"Freeing yourself was one thing, claiming ownership of that freed self was another.","Toni Morrison","Beloved"
"For, while the tale of how we suffer, and how we are delighted, and how we may triumph is never new, it always must be heard.","James Baldwin","Sonny's Blues"
"Sometimes being a friend means mastering the art of timing.","Octavia E. Butler","Kindred"
"I think it pisses God off if you walk by the color purple in a field somewhere and don't notice it.","Alice Walker","The Color Purple"
"There are years that ask questions and years that answer.","Zora Neale Hurston","Their Eyes Were Watching God"
"There is no greater agony than bearing an untold story inside you.","Maya Angelou","I Know Why the Caged Bird Sings"
"Your silence will not protect you.","Audre Lorde","The Cancer Journals"
"Imperialism leaves behind germs of rot which we must clinically detect and remove from our land but from our minds as well.","Frantz Fanon","The Wretched of the Earth"
"The practice of love offers no place of safety. We risk loss, hurt, pain. We risk being acted upon by forces outside our control.","bell hooks","All About Love: New Visions"
"Identity is not as transparent or unproblematic as we think.","Stuart Hall","Cultural Identity and Diaspora"
"The only reason you say that race was not an issue is because you wish it was not.","Chimamanda Ngozi Adichie","Americanah"
"Our lives are a battlefield on which is fought a continuous war between the forces that are pledged to confirm our humanity and those determined to dismantle it.","Ngũgĩ wa Thiong'o","Decolonising the Mind"
"The power of books, this marvelous invention of astute human intelligence.","Mariama Bâ","So Long a Letter"
"The business of womanhood is a heavy burden.","Tsitsi Dangarembga","Nervous Conditions"
"A film is not a political pamphlet, but it can make people think.","Ousmane Sembène","Various Interviews"
"It comes down to this: Black people were stripped of our identities when we were brought here, and it's been a quest since then to define who we are.","Spike Lee","Do the Right Thing Commentary"
"When you're a Black woman filmmaker, your very existence is a form of resistance.","Ava DuVernay","2016 Film Independent Forum"
"I think the aesthetic of Black cinema is empathy.","Barry Jenkins","If Beale Street Could Talk Press"
"Black people have always been the avant-garde.","Arthur Jafa","Love Is the Message, the Message Is Death"
"If you are free, you need to free somebody else.","Toni Morrison","1981 Speech"
"Love takes off the masks that we fear we cannot live without and know we cannot live within.","James Baldwin","The Fire Next Time"
"I'll tell you what freedom is to me: no fear.","Nina Simone","1968 Interview"
"The greatness of a man is not in how much wealth he acquires, but in his integrity and his ability to affect those around him positively.","Bob Marley","Various Interviews"
"I hold death in my pouch, I cannot die.","Fela Kuti","Various Interviews"
"Until you dig a hole, you plant a tree, you water it and make it survive, you haven't done a thing. You are just talking.","Wangari Maathai","Nobel Peace Prize Press"
"The day will come when history will speak. But it will not be the history which will be taught in Brussels, Paris, Washington or the United Nations.","Patrice Lumumba","Final Letter"
"He who feeds you, controls you.","Thomas Sankara","1984 Speech"
"It always seems impossible until it's done.","Nelson Mandela","Various Speeches"
"Black Consciousness is an attitude of the mind and a way of life.","Steve Biko","I Write What I Like"
"No one is going to give you the education you need to overthrow them.","Assata Shakur","Assata: An Autobiography"
"Radical simply means 'grasping things at the root'.","Angela Davis","Women, Culture & Politics"
"The revolution has always been in the hands of the young. The young always inherit the revolution.","Huey P. Newton","Various Speeches"
"The arc of the moral universe is long, but it bends toward justice.","Martin Luther King Jr.","1965 Speech in Montgomery"
"We declare our right on this earth to be a man, to be a human being, to be respected as a human being.","Malcolm X","1965 Resolution on African-American History"
"Up, you mighty race, accomplish what you will.","Marcus Garvey","Various Speeches"
"The cost of liberty is less than the price of repression.","W.E.B. Du Bois","John Brown"
"Power concedes nothing without a demand. It never did and it never will.","Frederick Douglass","1857 Speech"
"I am not going to die, I'm going home like a shooting star.","Sojourner Truth","Final Words"
"I freed a thousand slaves I could have freed a thousand more if only they knew they were slaves.","Harriet Tubman","Various Testimonies"
"The people must know before they can act, and there is no educator to compare with the press.","Ida B. Wells","Southern Horrors"
"Tremendous amounts of talent are lost to our society just because that talent wears a skirt or a dark skin.","Shirley Chisholm","Unbought and Unbossed"
"Look closely at the present you are constructing: it should look like the future you are dreaming.","Alice Walker","Various Essays"
"Love makes your soul crawl out from its hiding place.","Zora Neale Hurston","Their Eyes Were Watching God"
"I am the dream and the hope of the slave.","Maya Angelou","Still I Rise"
"Are you sure, sweetheart, that you want to be well?","Toni Cade Bambara","The Salt Eaters"
"I found god in myself and i loved her / i loved her fiercely.","Ntozake Shange","For Colored Girls Who Have Considered Suicide / When the Rainbow Is Enuf"
"Come celebrate with me that everyday something has tried to kill me and has failed.","Lucille Clifton","won't you celebrate with me"
"Does man love Art? Man visits Art, but squirms.","Gwendolyn Brooks","The Chicago Picasso"
"What happens to a dream deferred? Does it dry up like a raisin in the sun?","Langston Hughes","Harlem"
"If we must die, O let us nobly die.","Claude McKay","If We Must Die"
"I was leaving the South to fling myself into the unknown. I was taking a part of the South to transplant in alien soil.","Richard Wright","Black Boy"
"I am invisible, understand, simply because people refuse to see me.","Ralph Ellison","Invisible Man"
"Until the lions have their own historians, the history of the hunt will always glorify the hunter.","Chinua Achebe","Proverbial translation in essays"
"A tiger does not proclaim his tigritude, he pounces.","Wole Soyinka","1962 Kampala Writers Conference"
"Stories are the secret reservoir of values: change the stories individuals and nations live by and tell themselves, and you change the individuals and nations.","Ben Okri","The Mystery Feast"
"A reader is a person who reads. A writer is a person who rereads.","Teju Cole","Known and Strange Things"
"We are all local. We are all multi-local.","Taiye Selasi","TED Talk 2014"
"The family is like the forest: if you are outside it is dense; if you are inside you see that each tree has its own position.","Yaa Gyasi","Homegoing"
"Time is how you spend your love.","Zadie Smith","On Beauty"
"I am writing myself into the world.","Bernardine Evaristo","Girl, Woman, Other"
"Sometimes the truth is a lie that everybody agrees on.","Marlon James","A Brief History of Seven Killings"
"My body is a temple, not a tomb.","Safiya Sinclair","Cannibal"
"The cartographer is a man who loves his maps.","Kei Miller","The Cartographer Tries to Map a Way to Zion"
"Writing is a way of reclaiming what has been stolen.","Maryse Condé","Various Interviews"
"The archipelago is the symbol of a new world.","Édouard Glissant","Poetics of Relation"
"The word is a stone thrown into the water of the mind.","Kamau Brathwaite","The Arrivants"
"Memory is a treacherous landscape.","Alain Mabanckou","Tomorrow I'll Be Twenty"
"Art is never a substitute for life. It is the language of life.","Chris Abani","Various Lectures"
"The colony is not just a place, it is a state of mind.","Achille Mbembe","On the Postcolony"
"The development of Europe is part of the same dialectical process in which Africa was underdeveloped.","Walter Rodney","How Europe Underdeveloped Africa"
"Hide nothing from the masses of our people. Tell no lies.","Amílcar Cabral","Revolution in Guinea"
"Education is not a way to escape poverty, it is a way of fighting it.","Julius Nyerere","Various Speeches"
"Forward ever, backward never.","Kwame Nkrumah","Convention People's Party Slogan"
"Education is the most powerful weapon which you can use to change the world.","Nelson Mandela","1990 Speech"
"I’m not a modern-day anything. I’m Burna Boy. I’m the first of my kind.","Burna Boy","GQ Interview"
"My music is a reflection of my environment and the things I’ve gone through.","Wizkid","Various Interviews"
"We rise by lifting others.","Davido","Various Interviews"
"Black practices are a rich, textured, infinite, profound body of work.","Solange Knowles","Saint Heron Publications"
"If I’m gonna tell a real story, I’m gonna start with my name.","Kendrick Lamar","Good Kid, M.A.A.D City Era"
"We need to reshape our own perception of how we view ourselves. We have to step up as women and take the lead.","Beyoncé","Chime for Change"
"Life is so short you can't waste even a day subscribing to what someone thinks you can do versus knowing what you can do.","Virgil Abloh","Harvard GSD Lecture"
"You can't be born in Birmingham, Alabama, in 1955 and grow up in South Central near the Black Panthers headquarters, and not feel like you've got some kind of social responsibility.","Kerry James Marshall","Various Interviews"
"My work is about looking at things from a different angle.","Lorna Simpson","Various Interviews"
"I am trying to make sense of the world I live in.","Carrie Mae Weems","Kitchen Table Series Context"
"I'm always looking for the thing that's going to subvert my own expectations.","Kara Walker","Various Interviews"
"I am not a black artist, I am an artist.","Jean-Michel Basquiat","Various Interviews"
"I want to be the voice of my people.","Ousmane Sembène","Various Interviews"
"Cinema is magic in the service of dreams.","Djibril Diop Mambéty","Various Interviews"
"My films are my weapons. My camera is my gun.","Safi Faye","Various Interviews"
"A film is a piece of life.","Souleymane Cissé","Yeelen Press"
"We have a duty to tell our own stories.","Haile Gerima","Sankofa Press"
"I want to show the humanity of my people.","Charles Burnett","Various Interviews"
"I wanted to make a film about the beauty of black women.","Julie Dash","Daughters of the Dust Press Tour"
"I'm interested in truth, no matter how uncomfortable it is.","Steve McQueen","Various Interviews"
"Every story I create, creates me. I write to create myself.","Octavia E. Butler","Bloodchild and Other Stories"
"Science fiction is a tool to help you think.","Samuel R. Delany","Various Interviews"
"We have always been imagining our futures.","Nalo Hopkinson","Various Interviews"
"For a society to be truly great, it must be judged by how it treats its most vulnerable.","N.K. Jemisin","The City We Became"
"African science fiction is about the present.","Nnedi Okorafor","Various Essays"
"The alien is us.","Tade Thompson","Rosewater Press"
"I am not of this planet. I am from Saturn.","Sun Ra","Space Is the Place"
"Free your mind, and your ass will follow.","George Clinton","Funkadelic"
"A revolution is made by ordinary people.","C.L.R. James","The Black Jacobins"
"It is our duty to produce what we need.","Thomas Sankara","Women's Liberation and the African Freedom Struggle"
"The archive is a site of memory and forgetting.","John Akomfrah","The Stuart Hall Project"
"Culture is a site of struggle.","Stuart Hall","Cultural Studies"
"There is no pure black culture.","Paul Gilroy","The Black Atlantic"
"We must reinvent what it means to be human.","Sylvia Wynter","On Being Human as Praxis"
"Feminism is for everybody.","bell hooks","Feminism Is for Everybody"
"Home is not a place, it is a feeling.","Yaa Gyasi","Homegoing"
"Magic is in our blood.","Tomi Adeyemi","Children of Blood and Bone"
"True heroism is remarkably sober, very undramatic. It is not the urge to surpass all others at whatever cost, but the urge to serve others at whatever cost.","Arthur Ashe","A Hard Road to Glory"`;

const search = [ "“", "”", "«", "»", "‘", "’", "–", "—" ];
const replace = [ '"', '"', '"', '"', "'", "'", "-", "-" ];

let cleaned = raw;
for (let i = 0; i < search.length; i++) {
  cleaned = cleaned.split(search[i]).join(replace[i]);
}

const lines = cleaned.split("\n");
const quotes = [];
const seenHashes = new Set();

for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed) continue;
  
  // Surgical split on ","
  const parts = trimmed.split('","');
  if (parts.length >= 2) {
    const text = parts[0].replace(/^"/, "").trim();
    const author = parts[1].trim();
    const source = parts[2] ? parts[2].replace(/"$/, "").trim() : "";
    
    // De-duplicate in list
    const hash = text.toLowerCase();
    if (!seenHashes.has(hash)) {
      seenHashes.add(hash);
      quotes.push({ text, author, source });
    }
  }
}

console.log(JSON.stringify(quotes, null, 2));
console.log("// Total quotes: " + quotes.length);
